import type { APIRoute } from 'astro';
import { KEYWORDS, PRODUCT, absolute } from '../site';
import pkg from '../../../package.json';

/**
 * reach.pad.xml — the app described in PAD, the XML format download sites
 * read. Softpedia and its peers take the URL once and fetch it again on their
 * own schedule, so a new release reaches their listings without anyone
 * filling in a form.
 *
 * The version, date, installer link and size come from the latest GitHub
 * release at build time. The docs site is rebuilt by the release workflow, so
 * this follows every release by itself. If GitHub cannot be reached the build
 * still succeeds, with the version from package.json and a link to the
 * releases page: a slightly thinner file beats a failed deploy.
 */

const OWNER_REPO = PRODUCT.repo.replace('https://github.com/', '');

type Release = { tag_name: string; published_at: string; html_url: string; assets: { name: string; size: number; browser_download_url: string }[] };

async function latest(): Promise<Release | null> {
	try {
		const headers: Record<string, string> = { Accept: 'application/vnd.github+json', 'User-Agent': 'reach-docs' };
		if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
		const res = await fetch(`https://api.github.com/repos/${OWNER_REPO}/releases/latest`, { headers });
		return res.ok ? ((await res.json()) as Release) : null;
	} catch {
		return null;
	}
}

/** PAD fixes these lengths; a longer text is cut by whoever reads it. */
const DESCRIPTIONS = {
	45: 'Open-source SSH, SFTP, RDP and database tool',
	80: 'Free, open-source SSH client with SFTP, remote desktop and database tools',
	250: 'Reach is a free, open-source SSH client for Windows, macOS, Linux and Android: terminals in tabs, SFTP, port tunneling, remote desktop over RDP, an encrypted vault, and optional tools for databases, Ansible and OpenTofu.',
	450: 'Reach is a free, open-source SSH client for Windows, macOS, Linux and Android. It brings SSH terminals in tabs, an SFTP file explorer, jump hosts, port tunneling, a serial console and remote desktop over RDP into one app, with sessions and keys in an encrypted vault. Optional DevOps tools add a database workspace for PostgreSQL, MySQL, MariaDB, SQL Server, SQLite and Redis, plus Ansible and OpenTofu. No account, no subscription.',
	2000: `Reach is a free, open-source (MIT) SSH client and remote server manager for Windows, macOS, Linux and Android, built with a native interface instead of Electron.

Terminals and files: SSH terminals in tabs with split views, jump hosts and ~/.ssh/config import, an SFTP file explorer with drag-and-drop transfers and in-place compress and extract, local, remote and SOCKS port tunneling, and a serial console for routers and embedded devices.

Remote desktop: Windows desktops over RDP in a tab, with clipboard and file transfer both ways, a local folder shared in as a drive, and sound.

Security: sessions, passwords and SSH keys live in an encrypted vault, with optional cloud sync and shared vaults for teams. Host keys and RDP certificates are checked on first use and a changed one is always flagged.

DevOps tools, each switched on in Settings: a database workspace for PostgreSQL, MySQL, MariaDB, SQL Server, SQLite and Redis that browses, queries, edits rows, designs tables and backs up and restores, directly or through an SSH session; plus Ansible and OpenTofu workspaces.

Also included: command snippets, live server monitoring without agents, peer-to-peer terminal sharing, an optional AI assistant, an MCP server for AI coding tools, Lua plugins, themes and nine languages. No account, no subscription, no telemetry.`,
} as const;

for (const [limit, text] of Object.entries(DESCRIPTIONS)) {
	if (text.length > Number(limit)) {
		throw new Error(`reach.pad.xml: the ${limit}-character description is ${text.length} characters`);
	}
}

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export const GET: APIRoute = async () => {
	const release = await latest();
	const version = release?.tag_name.replace(/^v/, '') ?? pkg.version;
	const date = new Date(release?.published_at ?? Date.now());
	const installer = release?.assets.find((a) => a.name.endsWith('_x64-setup.exe'));
	const download = installer?.browser_download_url ?? `${PRODUCT.repo}/releases/latest`;
	const bytes = installer?.size ?? 0;
	const keywords = ['SSH', 'SFTP', 'RDP', 'terminal', 'database', ...KEYWORDS].join(', ');

	const xml = `<?xml version="1.0" encoding="UTF-8"?>
<XML_DIZ_INFO>
  <MASTER_PAD_VERSION_INFO>
    <MASTER_PAD_VERSION>4.0</MASTER_PAD_VERSION>
    <MASTER_PAD_EDITOR>Generated by the Reach docs build</MASTER_PAD_EDITOR>
    <MASTER_PAD_INFO>Portable Application Description, or PAD for short, is a data set that is used by shareware authors to disseminate information to anyone interested in their software products. To find out more go to http://pad.asp-software.org</MASTER_PAD_INFO>
  </MASTER_PAD_VERSION_INFO>
  <Company_Info>
    <Company_Name>alexandrosnt</Company_Name>
    <Address_1 />
    <City_Town />
    <State_Province />
    <Zip_Postal_Code />
    <Country />
    <Company_WebSite_URL>${esc(absolute(''))}</Company_WebSite_URL>
    <Contact_Info>
      <Author_First_Name>Alexander</Author_First_Name>
      <Author_Last_Name>Nt.</Author_Last_Name>
      <Author_Email />
      <Contact_First_Name>Alexander</Contact_First_Name>
      <Contact_Last_Name>Nt.</Contact_Last_Name>
      <Contact_Email />
    </Contact_Info>
    <Support_Info>
      <Sales_Email />
      <Support_Email />
      <General_Email />
      <Sales_Phone />
      <Support_Phone />
      <General_Phone />
      <Fax_Phone />
    </Support_Info>
  </Company_Info>
  <Program_Info>
    <Program_Name>${esc(PRODUCT.name)}</Program_Name>
    <Program_Version>${esc(version)}</Program_Version>
    <Program_Release_Month>${String(date.getUTCMonth() + 1).padStart(2, '0')}</Program_Release_Month>
    <Program_Release_Day>${String(date.getUTCDate()).padStart(2, '0')}</Program_Release_Day>
    <Program_Release_Year>${date.getUTCFullYear()}</Program_Release_Year>
    <Program_Cost_Dollars>0</Program_Cost_Dollars>
    <Program_Cost_Other_Code />
    <Program_Cost_Other />
    <Program_Type>Freeware</Program_Type>
    <Program_Release_Status>Major Update</Program_Release_Status>
    <Program_Install_Support>Install and Uninstall</Program_Install_Support>
    <Program_OS_Support>Win10,Win11,Mac OS X,Linux,Android</Program_OS_Support>
    <Program_Language>English,German,Spanish,French,Italian,Greek,Bulgarian,Russian,Chinese</Program_Language>
    <Program_Change_Info>${esc(`See the changelog: ${PRODUCT.repo}/blob/main/CHANGELOG.md`)}</Program_Change_Info>
    <Program_Specific_Category>Utilities</Program_Specific_Category>
    <Program_Category_Class>Network &amp; Internet::Terminal &amp; Telnet Clients</Program_Category_Class>
    <Program_System_Requirements>Windows 10 or 11 (64-bit), macOS 11 or later, a 64-bit Linux desktop, or Android 7 or later</Program_System_Requirements>
    <File_Info>
      <File_Size_Bytes>${bytes}</File_Size_Bytes>
      <File_Size_K>${Math.round(bytes / 1024)}</File_Size_K>
      <File_Size_MB>${(bytes / 1024 / 1024).toFixed(2)}</File_Size_MB>
    </File_Info>
    <Expire_Info>
      <Has_Expire_Info>N</Has_Expire_Info>
      <Expire_Count />
      <Expire_Based_On>Days</Expire_Based_On>
      <Expire_Other_Info />
      <Expire_Month />
      <Expire_Day />
      <Expire_Year />
    </Expire_Info>
  </Program_Info>
  <Program_Descriptions>
    <English>
      <Keywords>${esc(keywords)}</Keywords>
      <Char_Desc_45>${esc(DESCRIPTIONS[45])}</Char_Desc_45>
      <Char_Desc_80>${esc(DESCRIPTIONS[80])}</Char_Desc_80>
      <Char_Desc_250>${esc(DESCRIPTIONS[250])}</Char_Desc_250>
      <Char_Desc_450>${esc(DESCRIPTIONS[450])}</Char_Desc_450>
      <Char_Desc_2000>${esc(DESCRIPTIONS[2000])}</Char_Desc_2000>
    </English>
  </Program_Descriptions>
  <Web_Info>
    <Application_URLs>
      <Application_Info_URL>${esc(absolute(''))}</Application_Info_URL>
      <Application_Order_URL />
      <Application_Screenshot_URL>https://raw.githubusercontent.com/${OWNER_REPO}/main/assets/preview.png</Application_Screenshot_URL>
      <Application_Icon_URL>${esc(absolute('icon-512.png'))}</Application_Icon_URL>
      <Application_XML_File_URL>${esc(absolute('reach.pad.xml'))}</Application_XML_File_URL>
    </Application_URLs>
    <Download_URLs>
      <Primary_Download_URL>${esc(download)}</Primary_Download_URL>
      <Secondary_Download_URL>${esc(`${PRODUCT.repo}/releases/latest`)}</Secondary_Download_URL>
      <Additional_Download_URL_1 />
      <Additional_Download_URL_2 />
    </Download_URLs>
  </Web_Info>
  <Permissions>
    <Distribution_Permissions>Reach is free and open source under the MIT licence. It may be redistributed unchanged; link to ${esc(absolute(''))} or ${esc(PRODUCT.repo)} for the latest version.</Distribution_Permissions>
    <EULA>${esc(`MIT License. Full text: ${PRODUCT.repo}/blob/main/LICENSE`)}</EULA>
  </Permissions>
</XML_DIZ_INFO>
`;

	return new Response(xml, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } });
};
